# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config -id {Common 17-41} -limit 10000000

start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 2
  set_param xicom.use_bs_reader 1
  create_project -in_memory -part xc7a100tcsg324-1
  set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir C:/Users/tshum/OneDrive/Documents/FINAL_YEAR/1st_Semester/EEE4120F_HPEC/prac_four/Prac4/Tutorial/Tutorial.cache/wt [current_project]
  set_property parent.project_path C:/Users/tshum/OneDrive/Documents/FINAL_YEAR/1st_Semester/EEE4120F_HPEC/prac_four/Prac4/Tutorial/Tutorial.xpr [current_project]
  set_property ip_output_repo C:/Users/tshum/OneDrive/Documents/FINAL_YEAR/1st_Semester/EEE4120F_HPEC/prac_four/Prac4/Tutorial/Tutorial.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  add_files -quiet C:/Users/tshum/OneDrive/Documents/FINAL_YEAR/1st_Semester/EEE4120F_HPEC/prac_four/Prac4/Tutorial/Tutorial.runs/synth_1/project_1.dcp
  read_xdc C:/Users/tshum/OneDrive/Documents/FINAL_YEAR/1st_Semester/EEE4120F_HPEC/prac_four/Prac4/Tutorial/const.xdc
  link_design -top project_1 -part xc7a100tcsg324-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force project_1_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file project_1_drc_opted.rpt -pb project_1_drc_opted.pb -rpx project_1_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force project_1_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file project_1_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file project_1_utilization_placed.rpt -pb project_1_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file project_1_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
  phys_opt_design 
  write_checkpoint -force project_1_physopt.dcp
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force project_1_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file project_1_drc_routed.rpt -pb project_1_drc_routed.pb -rpx project_1_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file project_1_methodology_drc_routed.rpt -pb project_1_methodology_drc_routed.pb -rpx project_1_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file project_1_power_routed.rpt -pb project_1_power_summary_routed.pb -rpx project_1_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file project_1_route_status.rpt -pb project_1_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file project_1_timing_summary_routed.rpt -pb project_1_timing_summary_routed.pb -rpx project_1_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file project_1_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file project_1_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file project_1_bus_skew_routed.rpt -pb project_1_bus_skew_routed.pb -rpx project_1_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force project_1_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  catch { write_mem_info -force project_1.mmi }
  write_bitstream -force project_1.bit 
  catch {write_debug_probes -quiet -force project_1}
  catch {file copy -force project_1.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

